import { NextResponse } from 'next/server'

// Removed in v2 migration — see IF-92
// Per-user generation replaced by shared pipeline (cron/generate)
export async function POST() {
  return NextResponse.json(
    {
      error:
        'Per-user generation removed. Ideas are now generated by the shared pipeline.',
    },
    { status: 410 }
  )
}
